@startuml map_t
class value_t {
    + key
    + data
    + make_value(data, key) : value_t
}

class map_iterator_t {
    - value : value_t
    - parent : map_iterator_t
    - left : map_iterator_t
    - right : map_iterator_t
    + create()
    + destroy()
    + getValue() : value_t
}

class map_t {
    - begin : map_iterator_t
    - root : map_iterator_t
    - end : map_iterator_t
    - key_compare : int (*)(key1, key2)
    == Member functions ==
    + create
    + destroy
    -- Iterators --
    + begin() : map_iterator_t
    + end() : map_iterator_t
    -- Modifiers --
    + insert(value : value_t) : pair<map_iterator_t, bool>
    -- Lookup --
    + find(key) : map_iterator_t
}

map_iterator_t *-- value_t
map_t *-- map_iterator_t
@enduml